import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {NextUIProvider} from "@nextui-org/react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

function Providers ({children} : Readonly<{children: React.ReactNode}>){
  return (
    <NextUIProvider>
      {children}
    </NextUIProvider>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          </Providers>
        </body>
    </html>
  );
}
